[package]
name = "ckb-test-chain-utils"
version = "0.120.0-rc4"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2021"
license = "MIT"
description = "Provide several functions used for testing."
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
ckb-types = { path = "../types", version = "= 0.120.0-rc4" }
ckb-db = { path = "../../db", version = "= 0.120.0-rc4" }
ckb-store = { path = "../../store", version = "= 0.120.0-rc4" }
ckb-chain-spec = { path = "../../spec", version = "= 0.120.0-rc4" }
ckb-dao-utils = { path = "../dao/utils", version = "= 0.120.0-rc4" }
ckb-dao = { path = "../dao", version = "= 0.120.0-rc4" }
ckb-traits = { path = "../../traits", version = "= 0.120.0-rc4" }
ckb-systemtime = { path = "../systemtime", version = "= 0.120.0-rc4" }
ckb-resource = { path = "../../resource", version = "= 0.120.0-rc4" }
ckb-db-schema = { path = "../../db-schema", version = "= 0.120.0-rc4" }
ckb-util = { path = "..", version = "= 0.120.0-rc4" }
tempfile.workspace = true

[dev-dependencies]
ckb-systemtime = { path = "../systemtime", version = "= 0.120.0-rc4", features = [
    "enable_faketime",
] }
