[package]
name = "ckb-notify"
version = "0.120.0-rc3"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2021"
license = "MIT"
description = "TODO(doc): @quake crate description"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
ckb-logger = { path = "../util/logger", version = "= 0.120.0-rc3" }
ckb-app-config  = { path = "../util/app-config", version = "= 0.120.0-rc3" }
ckb-types = { path = "../util/types", version = "= 0.120.0-rc3" }
ckb-stop-handler = { path = "../util/stop-handler", version = "= 0.120.0-rc3" }
ckb-async-runtime = { path = "../util/runtime", version = "= 0.120.0-rc3" }
tokio = { version = "1", features = ["sync"] }

[dev-dependencies]
