[package]
name = "ckb-dao"
version = "0.120.0-rc3"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2021"
description = "This crate provides implementation to calculate dao field"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
byteorder = "1.3.1"
ckb-types = { path = "../types", version = "= 0.120.0-rc3" }
ckb-chain-spec = { path = "../../spec", version = "= 0.120.0-rc3" }
ckb-dao-utils = { path = "./utils", version = "= 0.120.0-rc3" }
ckb-traits = { path = "../../traits", version = "= 0.120.0-rc3" }

[dev-dependencies]
ckb-db = { path = "../../db", version = "= 0.120.0-rc3" }
ckb-db-schema = { path = "../../db-schema", version = "= 0.120.0-rc3" }
ckb-store = { path = "../../store", version = "= 0.120.0-rc3" }
tempfile.workspace = true
