[package]
name = "ckb-verification"
version = "0.120.0-rc5"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2021"
description = "The CKB verification"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
ckb-types = { path = "../util/types", version = "= 0.120.0-rc5" }
ckb-script = { path = "../script", version = "= 0.120.0-rc5" }
ckb-pow = { path = "../pow", version = "= 0.120.0-rc5" }
ckb-systemtime = { path = "../util/systemtime", version = "= 0.120.0-rc5" }
lru = "0.7.1"
ckb-traits = { path = "../traits", version = "= 0.120.0-rc5" }
ckb-chain-spec = { path = "../spec", version = "= 0.120.0-rc5" }
ckb-dao = { path = "../util/dao", version = "= 0.120.0-rc5" }
ckb-dao-utils = { path = "../util/dao/utils", version = "= 0.120.0-rc5" }
ckb-error = { path = "../error", version = "= 0.120.0-rc5" }
derive_more = { version = "1", default-features = false, features = [
    "display",
] }
ckb-verification-traits = { path = "./traits", version = "= 0.120.0-rc5" }
tokio = { version = "1", features = ["sync", "macros"] }


[dev-dependencies]
ckb-test-chain-utils = { path = "../util/test-chain-utils", version = "= 0.120.0-rc5" }
ckb-resource = { path = "../resource", version = "= 0.120.0-rc5" }
ckb-systemtime = { path = "../util/systemtime", version = "= 0.120.0-rc5", features = [
    "enable_faketime",
] }
