[package]
name = "ckb-async-runtime"
version = "0.120.0-rc5"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2021"
description = "CKB async runtime wrapper."
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
tokio = { version = "1", features = ["rt", "sync"] }
ckb-logger = { path = "../logger", version = "= 0.120.0-rc5" }
ckb-spawn = { path = "../spawn", version = "= 0.120.0-rc5" }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
tokio = { version = "1", features = ["rt-multi-thread"] }


[target.'cfg(target_family = "wasm")'.dependencies]
wasm-bindgen-futures = "0.4"
