[package]
name = "ckb-launcher"
version = "0.120.0-rc5"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2021"
description = "CKB tool to import/export chain data."
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-types = { path = "../types", version = "= 0.120.0-rc5" }
ckb-store = { path = "../../store", version = "= 0.120.0-rc5" }
ckb-app-config = { path = "../app-config", version = "= 0.120.0-rc5" }
ckb-logger = { path = "../logger", version = "= 0.120.0-rc5" }
ckb-build-info = { path = "../build-info", version = "= 0.120.0-rc5" }
ckb-jsonrpc-types = { path = "../jsonrpc-types", version = "= 0.120.0-rc5" }
ckb-chain = { path = "../../chain", version = "= 0.120.0-rc5" }
ckb-shared = { path = "../../shared", version = "= 0.120.0-rc5" }
ckb-network = { path = "../../network", version = "= 0.120.0-rc5" }
ckb-rpc = { path = "../../rpc", version = "= 0.120.0-rc5" }
ckb-resource = { path = "../../resource", version = "= 0.120.0-rc5" }
ckb-network-alert = { path = "../network-alert", version = "= 0.120.0-rc5" }
ckb-sync = { path = "../../sync", version = "= 0.120.0-rc5" }
ckb-verification = { path = "../../verification", version = "= 0.120.0-rc5" }
ckb-verification-traits = { path = "../../verification/traits", version = "= 0.120.0-rc5" }
ckb-async-runtime = { path = "../runtime", version = "= 0.120.0-rc5" }
ckb-channel = { path = "../channel", version = "= 0.120.0-rc5" }
ckb-tx-pool = { path = "../../tx-pool", version = "= 0.120.0-rc5" }
ckb-light-client-protocol-server = { path = "../light-client-protocol-server", version = "= 0.120.0-rc5" }
ckb-block-filter = { path = "../../block-filter", version = "= 0.120.0-rc5" }

[features]
with_sentry = [
    "ckb-sync/with_sentry",
    "ckb-network/with_sentry",
    "ckb-app-config/with_sentry"
]
portable = ["ckb-shared/portable"]
march-native = ["ckb-shared/march-native"]
