[package]
name = "ckb-migrate"
version = "0.120.0-rc5"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2021"
description = "TODO(doc): @eval-exec crate description"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-migration-template = { path = "migration-template", version = "= 0.120.0-rc5" }
ckb-db = { path = "../../db", version = "= 0.120.0-rc5" }
ckb-error = { path = "../../error", version = "= 0.120.0-rc5" }
ckb-db-schema = { path = "../../db-schema", version = "= 0.120.0-rc5" }
ckb-db-migration = { path = "../../db-migration", version = "= 0.120.0-rc5" }
ckb-app-config = { path = "../app-config", version = "= 0.120.0-rc5" }
ckb-types = { path = "../types", version = "= 0.120.0-rc5" }
ckb-store = { path = "../../store", version = "= 0.120.0-rc5" }
ckb-chain-spec = { path = "../../spec", version = "= 0.120.0-rc5" }
ckb-hash = { path = "../hash", version = "= 0.120.0-rc5" }
tempfile.workspace = true
num_cpus = "1.10"

[dev-dependencies]
ckb-systemtime = {path = "../systemtime", version = "= 0.120.0-rc5", features = ["enable_faketime"]  }

[features]
portable = ["ckb-db/portable", "ckb-db-migration/portable"]
march-native = ["ckb-db/march-native", "ckb-db-migration/march-native"]
