[package]
name = "ckb-instrument"
version = "0.120.0-rc3"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2021"
description = "CKB tool to import/export chain data."
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
ckb-types = { path = "../types", version = "= 0.120.0-rc3" }
ckb-chain = { path = "../../chain", version = "= 0.120.0-rc3" }
ckb-chain-iter = { path = "../chain-iter", version = "= 0.120.0-rc3" }
ckb-shared = { path = "../../shared", version = "= 0.120.0-rc3" }
ckb-jsonrpc-types = { path = "../jsonrpc-types", version = "= 0.120.0-rc3" }
serde_json = "1.0"
indicatif = { version = "0.16", optional = true }

[features]
progress_bar = ["indicatif"]
